language: node_js
node_js:
- 6.9.1
sudo: false
cache:
  directories:
  - /home/travis/.local
  - node_modules
  - $(npm config get cache)
before_install:
- npm config set progress false
- npm config set spin false
install:
- pip install --user -U awscli
- npm install
script:
- npm test
deploy:
- provider: script
  script: ./scripts/deploy.sh
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAIVHGQ4QNDGEF4ZGA
  - secure: A9DmclIqWpSNGVGzV3yEx7xQQu0JLM7HmPpdnx8YTO/qN/A0kYuPQBUEbiJSx/J/VPC/kAu2W2RT2DiXUknejk8yvR7swFS8tN7OKO2EzIlVyTq3QoPCXLxw7TYW2NGzNBqdZRSJBkPvkat1FMR80z4JyYLw4PJEpXd4dT8yAyZ3DOxZZfxu47ORVYBApQ/I2J6p4HRMzjYZdZYhtniaQcVWPsD6GiDBGTIlOo1UgtLWggZ02GjJMfJi53wEdJwAB6Ak6G3/E9C9jWe7gxhNDYgSf8Ssj2PsQuO9QQIrITawUT9x04GTD8VxYTZR7SVh00QFAgMErpMlm3IIsaJuG0rfZ/L4O25aTZ0m8I/O5c+H7rz2ggFWgad8npS/UG1X92DwYoUboKV6OZXIGKMkg5yd5gibQiUJs1IkX6aVhMWv0SUITyWbir59ciiqeF5uv+q3gkrzy8H9sRB7aF74B9E+YZP2P5ApORiddhk5S5NheKmOpJD8f0jVewsHsaxwbL2cNzKqZ2ikftUtORDKjkLeH8HE4lDkx0jQwR6rnIe3yyjFZiOkMUkenHvmgGUGBcLNXG90zFKVFY3AIko+nu90CxVJlvg5RZ9fbKt88ZH+VuwHaKXBg/WyrjbNZ6Abi8RYF5Ezje3UAwh3s+Zov6O/mQp855yEZz5KuoAzvC4=
